const ADD_ITEM_TO_TODO = 'ADD_ITEM_TO_TODO';
const REMOVE_ITEM_FROM_TODO = 'REMOVE_ITEM_FROM_TODO';
const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';

export default {
  ADD_ITEM_TO_TODO,
  REMOVE_ITEM_FROM_TODO,
  UPDATE_TODO_ITEM
};